---
os: linux

language: shell

services:
- docker

git:
  depth: 2

branches:
  only:
  - master

env:
  global:
  - REPO=midnighter/conda-mnx
  - VERSION=0.1.0
  - IMAGE="${REPO}:${VERSION}"
  - LATEST="${REPO}:latest"

before_install:
- echo "${DOCKER_PASSWORD}" | docker login --username="${DOCKER_USER}" --password-stdin
- docker pull midnighter/conda-base:3.8-latest

install:
- "docker build --tag ${IMAGE} --tag ${LATEST} ."

script:
- "docker run --tty ${LATEST} mnx-sdk --help"
- "docker run --tty ${LATEST} mnx-assets --help"
- "docker run --tty ${LATEST} mnx-post --help"

after_success:
- "docker push ${IMAGE}"
- "docker push ${LATEST}"

notifications:
  email:
    on_success: never
    on_failure: always
